// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq8CEUmePoeiB7yke5HreH6plJZ9953Ss',
    appId: '1:299307200563:web:355af59d2f992e08d77346',
    messagingSenderId: '299307200563',
    projectId: 'signuplogin-b9c89',
    authDomain: 'signuplogin-b9c89.firebaseapp.com',
    storageBucket: 'signuplogin-b9c89.appspot.com',
    measurementId: 'G-2E7GCW3YJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiYtTjxzTVLC-KZlGNb65PZVgTYTPp-F4',
    appId: '1:299307200563:android:d782f969af9e0293d77346',
    messagingSenderId: '299307200563',
    projectId: 'signuplogin-b9c89',
    storageBucket: 'signuplogin-b9c89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ8S-9Hm8QdPtisNsvZIJd4cBV2CMsU2E',
    appId: '1:299307200563:ios:a881d0f5ada72026d77346',
    messagingSenderId: '299307200563',
    projectId: 'signuplogin-b9c89',
    storageBucket: 'signuplogin-b9c89.appspot.com',
    iosBundleId: 'com.example.signuplogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ8S-9Hm8QdPtisNsvZIJd4cBV2CMsU2E',
    appId: '1:299307200563:ios:a881d0f5ada72026d77346',
    messagingSenderId: '299307200563',
    projectId: 'signuplogin-b9c89',
    storageBucket: 'signuplogin-b9c89.appspot.com',
    iosBundleId: 'com.example.signuplogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq8CEUmePoeiB7yke5HreH6plJZ9953Ss',
    appId: '1:299307200563:web:637b0473edc62f9dd77346',
    messagingSenderId: '299307200563',
    projectId: 'signuplogin-b9c89',
    authDomain: 'signuplogin-b9c89.firebaseapp.com',
    storageBucket: 'signuplogin-b9c89.appspot.com',
    measurementId: 'G-X11QK4F0TH',
  );
}
